apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-router-port-forward
  namespace: util
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-router-port-forward
  template:
    metadata:
      labels:
        app: kube-router-port-forward
    spec:
      serviceAccountName: kube-router-port-forward
      containers:
      - name: kube-router-port-forward
        image: clbx/kube-router-port-forward
        imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-router-port-forward
  namespace: util
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-router-port-forward
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-router-port-forward
subjects:
- kind: ServiceAccount
  name: kube-router-port-forward
  namespace: util
roleRef:
  kind: ClusterRole
  name: kube-router-port-forward
  apiGroup: rbac.authorization.k8s.io
