apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: util
  annotations:
    kube-router-port-forward/ports: "1234"
spec:
  selector:
    app: test-service
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.3.152
